name: halal_check
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #Firebasee packages
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2

  #image packages
  cached_network_image: ^3.3.1
  image_picker: ^1.1.1
  image_cropper: ^5.0.1
  time_range_picker: ^2.3.0
  file_picker: ^8.0.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  intl: ^0.19.0
  flutter_image_compress: ^2.2.0
  lottie: ^3.1.1
  country_picker: ^2.0.26

  #DI
  get_it: ^7.7.0

  cupertino_icons: ^1.0.6
  animations: ^2.0.11
  flutter_screenutil: ^5.9.0
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.2.8
  latlng: ^2.0.7
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  google_places_flutter: ^2.0.8
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  # flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/Euclid Circular A Bold Italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Euclid Circular A Bold.ttf
          weight: 700

        - asset: assets/fonts/Euclid Circular A SemiBold Italic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Euclid Circular A SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Euclid Circular A Medium Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Euclid Circular A Medium.ttf
          weight: 500

        - asset: assets/fonts/Euclid Circular A Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Euclid Circular A Regular.ttf
          weight: 400

        - asset: assets/fonts/Euclid Circular A Light Italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Euclid Circular A Light.ttf
          weight: 300
